### ISSUE TITLE
qslack: workflow stopped working

### ISSUE THREAD

**Issue by Necior** [landmaj/qbot#26]
See https://github.com/landmaj/qbot/actions/runs/3139150020 for an example of a failed build.

It looks like the problem lies in `pyproject.toml`, in `betterproto` definition:

```toml
[tool.poetry.dev-dependencies]
betterproto = {extras = ["compiler"], version = "grpcio-tools"}
```
